name: CI

on:
  push:
    branches: [ master, main, tests ]
  pull_request:
    branches: [ master, main, tests ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependancies
        run: npm ci
      - name: Test application
        run: npm test
      - name: run all tests
        run: a  